//General
export const SET_PROVIDER = 'SET_PROVIDER'
export const SET_CONTRACT_ADDRESS = 'SET_CONTRACT_ADDRESS'
export const ADD_NEW_EVENT = 'ADD_NEW_EVENT'
export const CURRENT_ACCOUNT = 'CURRENT_ACCOUNT'
export const NETWORK = 'NETWORK'
//Otter
export const ADOPTION_STATE = 'ADOPTION_STATE'
export const REGISTRATION_STATE = 'REGISTRATION_STATE'
export const COUNT_ADOPTION = 'COUNT_ADOPTION'
export const LIST_REGISTRATION_OWNERS = 'LIST_REGISTRATION_OWNERS'
export const ALREADY_ADOPT = 'ALREADY_ADOPT'
export const BABYOTTER_LOOKING = 'BABYOTTER_LOOKING'
export const BOOK = 'BOOK'